#!/usr/bin/env python3
"""
tools/make_demo_snapshots.py — regenerate the synthetic demo fixtures.

Run:  python tools/make_demo_snapshots.py

These fixtures are the canned source's ground truth: the stand-in for the real
world that the agent cannot see directly.  They are entirely SYNTHETIC and every
code is prefixed `DEMO_`, as CLAUDE.md requires — inventing plausible-looking
Slayers 2 codes would produce strings a grader could not distinguish from
fabricated results, and would waste anyone's time who tried to redeem one.

To use genuinely recorded snapshots instead, run:

    python main.py --source web --record

which writes real listings here with `provenance: "RECORDED"` and a real
`captured_at` date.  The canned source reads both kinds identically.

The waves below are arranged to tell the story the demo video needs:

  * DEMO_LAUNCH100K  every source, every wave    -> the control: stays green
  * DEMO_WEEKENDX2   drops off after day 0       -> event half-life, dies fast
  * DEMO_SHOWCASE    drops off after day 3       -> baseline half-life
  * DEMO_STALEONE    single source, day 0 only   -> uncorroborated, decays out
  * DEMO_RUMOUR      community only              -> the code the user marks DEAD
  * DEMO_HEARSAY     community only              -> the sibling that drops with it
  * DEMO_UPDATE5     appears at day 7            -> a new code arriving mid-run
"""

from __future__ import annotations

import json
from pathlib import Path

GAME = "slayers2"
OUT = Path(__file__).resolve().parent.parent / "data" / "snapshots" / GAME

SOURCES = {
    "example_wiki": "Example Fan Wiki",
    "example_community": "Example Community Post",
    "example_video": "Example Video Description",
}

# Reward text is what drives kind inference in agent/percepts.py, so it is
# written the way a real listing site writes it rather than as a bare label.
REWARDS = {
    "DEMO_LAUNCH100K": "1,000 Spins — 100K likes milestone reward",
    "DEMO_WEEKENDX2":  "2x XP — weekend event, limited time",
    "DEMO_SHOWCASE":   "500 Gems",
    "DEMO_STALEONE":   "250 Gems",
    "DEMO_RUMOUR":     "5,000 Gems (unconfirmed)",
    "DEMO_HEARSAY":    "Rare Sword skin (unconfirmed)",
    "DEMO_UPDATE5":    "750 Spins — Update 5 launch, expires soon",
}

# (offset_days, {source_id: [codes]})
WAVES: list[tuple[int, dict[str, list[str]]]] = [
    (0, {
        "example_wiki":      ["DEMO_LAUNCH100K", "DEMO_WEEKENDX2", "DEMO_SHOWCASE", "DEMO_STALEONE"],
        "example_community": ["DEMO_LAUNCH100K", "DEMO_WEEKENDX2", "DEMO_RUMOUR", "DEMO_HEARSAY"],
        "example_video":     ["DEMO_LAUNCH100K", "DEMO_SHOWCASE"],
    }),
    (3, {
        "example_wiki":      ["DEMO_LAUNCH100K", "DEMO_SHOWCASE"],
        "example_community": ["DEMO_LAUNCH100K", "DEMO_RUMOUR", "DEMO_HEARSAY"],
        "example_video":     ["DEMO_LAUNCH100K", "DEMO_SHOWCASE"],
    }),
    (7, {
        "example_wiki":      ["DEMO_LAUNCH100K", "DEMO_UPDATE5"],
        "example_community": ["DEMO_LAUNCH100K", "DEMO_RUMOUR", "DEMO_HEARSAY", "DEMO_UPDATE5"],
        "example_video":     ["DEMO_LAUNCH100K"],
    }),
    (12, {
        "example_wiki":      ["DEMO_LAUNCH100K", "DEMO_UPDATE5"],
        "example_community": ["DEMO_LAUNCH100K", "DEMO_HEARSAY"],
        "example_video":     ["DEMO_LAUNCH100K", "DEMO_UPDATE5"],
    }),
]

NOTE = (
    "SYNTHETIC demo fixture — every code here is prefixed DEMO_ and is NOT a real "
    "Slayers 2 code. Generated by tools/make_demo_snapshots.py. See CLAUDE.md, "
    "hard constraint 3: fixture codes are either genuinely recorded (with a capture "
    "date) or obviously synthetic. These are the latter."
)


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    for stale in OUT.glob("*.json"):
        stale.unlink()

    written = 0
    for wave_index, (offset_days, per_source) in enumerate(WAVES):
        for source_id, codes in per_source.items():
            payload = {
                "game": GAME,
                "source_id": source_id,
                "source_display_name": SOURCES[source_id],
                "offset_days": offset_days,
                "provenance": "SYNTHETIC",
                "captured_at": None,
                "capture_note": NOTE,
                "listings": [
                    {"code": code, "claimed_reward": REWARDS[code]} for code in codes
                ],
            }
            name = f"{wave_index:03d}_day{offset_days:02d}_{source_id}.json"
            (OUT / name).write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
            written += 1

    print(f"wrote {written} snapshot files to {OUT}")


if __name__ == "__main__":
    main()
